"""empty message

Revision ID: f0a9471554e2
Revises: 3593c7fead91
Create Date: 2022-05-20 12:40:32.109132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a9471554e2'
down_revision = '3593c7fead91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('location', sa.String(length=50), nullable=False))
    op.drop_column('artists', 'artist_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('artist_location', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('artists', 'location')
    # ### end Alembic commands ###
