"""empty message

Revision ID: 3593c7fead91
Revises: 52a8b16082a9
Create Date: 2022-05-20 12:38:41.303584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3593c7fead91'
down_revision = '52a8b16082a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('first_name', sa.String(length=15), nullable=False))
    op.add_column('artists', sa.Column('last_name', sa.String(length=15), nullable=False))
    op.drop_column('artists', 'artist_lastname')
    op.drop_column('artists', 'artist_firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('artist_firstname', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('artists', sa.Column('artist_lastname', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_column('artists', 'last_name')
    op.drop_column('artists', 'first_name')
    # ### end Alembic commands ###
