"""empty message

Revision ID: 52a8b16082a9
Revises: 23c3fa4693aa
Create Date: 2022-05-20 12:27:35.304158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a8b16082a9'
down_revision = '23c3fa4693aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=15), nullable=False),
    sa.Column('last_name', sa.String(length=15), nullable=False),
    sa.Column('artworks_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artworks_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collector_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['collectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('customer_accounts')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('customers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='customers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('customer_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='customer_accounts_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer_accounts_pkey'),
    sa.UniqueConstraint('email', name='customer_accounts_email_key')
    )
    op.drop_table('collector_accounts')
    op.drop_table('collectors')
    # ### end Alembic commands ###
