"""empty message

Revision ID: 172b43cfb7fc
Revises: 3f67e2154d90
Create Date: 2022-05-20 13:32:17.615103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172b43cfb7fc'
down_revision = '3f67e2154d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('art_category_category_id_fkey', 'art_category', type_='foreignkey')
    op.create_foreign_key(None, 'art_category', 'categories', ['category_id'], ['category_id'])
    op.add_column('categories', sa.Column('category_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'category_id')
    op.drop_constraint(None, 'art_category', type_='foreignkey')
    op.create_foreign_key('art_category_category_id_fkey', 'art_category', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
