"""empty message

Revision ID: 3f67e2154d90
Revises: f0a9471554e2
Create Date: 2022-05-20 12:54:11.711959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f67e2154d90'
down_revision = 'f0a9471554e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collector_accounts', sa.Column('collector_id', sa.Integer(), nullable=False))
    op.drop_constraint('collector_accounts_customer_id_fkey', 'collector_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'collector_accounts', 'collectors', ['collector_id'], ['id'])
    op.drop_column('collector_accounts', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collector_accounts', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'collector_accounts', type_='foreignkey')
    op.create_foreign_key('collector_accounts_customer_id_fkey', 'collector_accounts', 'collectors', ['customer_id'], ['id'])
    op.drop_column('collector_accounts', 'collector_id')
    # ### end Alembic commands ###
